### ISSUE TITLE
Compatible with Zim 0.73.2?

### ISSUE THREAD

**Issue by sojusnik** [e3rd/zim-plugin-copy-rich#1]
I've installed this plugin with all dependencies and enabled it under plugins, restarted, but I can't see `Copy Rich HTML` in `Edit`. Is this plugin still compatible with the latest version?

**Comment by e3rd** [comment]
Hi, I'll have to test this the next week, thanks for reporting

**Comment by sojusnik** [comment]
Thanks!

BTW, is there some restriction why the "Copy Rich HTML" entry can't be placed in the right click menu under "copy as"?

**Comment by e3rd** [comment]
Would you please start zim with `zim --debug --standalone` and go to Edit / Preferences / Plugins? Some output concerning the plugin should be produced in that case. 

> placed in the right click menu under "copy as"

I don't see any restriction and I'm open to all pull requests. ~~I tried to find the place where should I implement this for few minutes but I did not find it. :(~~ I found it in `pageview.py/_default_do_populate_popup`. If you'd found a plugin that adds an item in the popup menu, I might be able to replicate the functionality.

**Comment by sojusnik** [comment]
> Would you please start zim with `zim --debug --standalone` and go to Edit / Preferences / Plugins? Some output concerning the plugin should be produced in that case.

No relevant output here.

Curiously, when using the [stable](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim?field.series_filter=focal) version of Zim, then the entry is present in the `edit` menu, but not with the [snapshot](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots?field.series_filter=focal) version.

> I don't see any restriction and I'm open to all pull requests. ~I tried to find the place where should I implement this for few minutes but I did not find it. :(~ I found it in `pageview.py/_default_do_populate_popup`. If you'd found a plugin that adds an item in the popup menu, I might be able to replicate the functionality.

Since I'm not into coding, I can't help you on this, sorry. Didn't find a plugin that adds an entry to the right-click menu either.

**Comment by e3rd** [comment]
> but not with the snapshot version.

Strange :o

**Comment by quesada** [comment]
Can confirm plugin is not listed under prefs > plugins.
zim 0.73.4, linux

**Comment by e3rd** [comment]
Hello,
1) Would you please start zim with `zim --debug --standalone` and go to Edit / Preferences / Plugins? Some output concerning the plugin should be produced in that case. 
2) What directory you put the file to? Are there any plugins in that directory that works?

**Comment by quesada** [comment]
Actually, I was wrong, it's working. I forgot to close all windows of zim. It's beautiful, thanks for making this plugin!

**Comment by e3rd** [comment]
Thanks a lot, glad to hear it's useful!

**Comment by sojusnik** [comment]
This plugin still doesn't work with the snapshot version of Zim, in my case with v0.73.5 from [here](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots) under Ubuntu 21.04.

**Comment by e3rd** [comment]
Does current master works to you now please?

**Comment by sojusnik** [comment]
Works now, thanks!

Would love to see it in the "copy as" right click menu soon.

**Comment by e3rd** [comment]
Unfortunately, I don't know how to do that :( Happily using <kbd>Ctrl+Shift+S</kbd> #5 

Thanks for having tested! :)
