### ISSUE TITLE
New lines not copying correctly?

### ISSUE THREAD

**Issue by timbze** [e3rd/zim-plugin-copy-rich#2]
Hey appreciate your work on this plugin!

I just installed it, bold is copying correctly, but new lines are getting removed. 

For example, regular copy leaves new lines intact, but all rich text (i.e. bold etc) gets removed.

With rich copy, when I copy this:
**Line 1 Bold**
Line 2
Line 3

I get this:
**Line 1 Bold** Line 2 Line 3

I have Zim 0.73.2
Ubuntu 20.10

**Comment by timbze** [comment]
Just found out when it's a double new-line then it works.

This works:
**Line 1 Bold**

Line 2

**Comment by e3rd** [comment]
Hello, thanks for your investigation, unfortunately, this plugin was meant as a quick wrapper and I fear not to have enough of time to dive into this. I'll welcome any PR however. See the main file, it's very short.  
Have a nice day
